// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2023_2C_F_Estacionamiento.Data;

#nullable disable

namespace _2023_2C_F_Estacionamiento.Data.Migrations
{
    [DbContext(typeof(EstacionamientoContext))]
    [Migration("20231002203642_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.ClienteVehiculo", b =>
                {
                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.Property<bool>("ResponsablePrincipal")
                        .HasColumnType("bit");

                    b.HasKey("ClienteId", "VehiculoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("ClientesVehiculo");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CodPostal")
                        .HasColumnType("bigint");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Estancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Estancia");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EstanciaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.HasKey("Id");

                    b.HasIndex("EstanciaId")
                        .IsUnique();

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Telefono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("CodArea")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Telefono");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AnioFabricacion")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Patente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Cliente", b =>
                {
                    b.HasBaseType("_2023_2C_F_Estacionamiento.Models.Persona");

                    b.Property<long>("Cuil")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Empleado", b =>
                {
                    b.HasBaseType("_2023_2C_F_Estacionamiento.Models.Persona");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("DireccionId")
                        .HasColumnType("int");

                    b.HasIndex("DireccionId");

                    b.HasDiscriminator().HasValue("Empleado");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.ClienteVehiculo", b =>
                {
                    b.HasOne("_2023_2C_F_Estacionamiento.Models.Cliente", "Cliente")
                        .WithMany("VehiculosAutorizados")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2023_2C_F_Estacionamiento.Models.Vehiculo", "Vehiculo")
                        .WithMany("PersonasAutorizadas")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Direccion", b =>
                {
                    b.HasOne("_2023_2C_F_Estacionamiento.Models.Cliente", "Cliente")
                        .WithOne("Direccion")
                        .HasForeignKey("_2023_2C_F_Estacionamiento.Models.Direccion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Estancia", b =>
                {
                    b.HasOne("_2023_2C_F_Estacionamiento.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2023_2C_F_Estacionamiento.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Pago", b =>
                {
                    b.HasOne("_2023_2C_F_Estacionamiento.Models.Estancia", "Estancia")
                        .WithOne("pago")
                        .HasForeignKey("_2023_2C_F_Estacionamiento.Models.Pago", "EstanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estancia");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Telefono", b =>
                {
                    b.HasOne("_2023_2C_F_Estacionamiento.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2023_2C_F_Estacionamiento.Models.Persona", "Persona")
                        .WithMany("Telefonos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Empleado", b =>
                {
                    b.HasOne("_2023_2C_F_Estacionamiento.Models.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId");

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Estancia", b =>
                {
                    b.Navigation("pago")
                        .IsRequired();
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Persona", b =>
                {
                    b.Navigation("Telefonos");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Vehiculo", b =>
                {
                    b.Navigation("PersonasAutorizadas");
                });

            modelBuilder.Entity("_2023_2C_F_Estacionamiento.Models.Cliente", b =>
                {
                    b.Navigation("Direccion");

                    b.Navigation("VehiculosAutorizados");
                });
#pragma warning restore 612, 618
        }
    }
}
